version: '2.1'

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    volumes:
      - './flags:/tmp/flags'
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - '80:80'
