version: '2.1'

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    image: ghcr.io/thentcompany/send-me-money-backend:latest
    volumes:
      - './flags:/tmp/flags'
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    image: ghcr.io/thentcompany/send-me-money-frontend:latest
    ports:
      - '80:80'
