[x86_64-unknown-linux-musl]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[wasm32-unknown-unknown]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

