name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:

  docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache docker
      id: cache-docker
      uses: actions/cache@v3
      with:
        path: /home/runner/.docker/buildkit
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
            ${{ runner.os }}-docker-
            ${{ runner.os }}-

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
       registry: ghcr.io
       username: ${{ github.actor }}
       password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker images
      run: DOCKER_BUILDKIT=1 docker-compose build
    - name: Deploy the Docker images
      run: docker-compose push
